<a href="https://colab.research.google.com/github/amandahaff/MAT422/blob/main/1_2_HW_Haffner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# Amanda Haffner
#HW 1.2 Elements of Linear Algebra
# linear spaces, othogonality, gram-schmidt, eiganvalues and vectors

# "A linear combination in linear algebra is a new vector constructed from a
# subset by multiplying each vector by a constant and adding the results.
# A linear subspace is a result of linear combination"

import numpy as np
# Creating vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

print("Vector A:", vector_a)
print("vector B:", vector_b)

# Vector addition
addition = vector_a + vector_b
print("vector addition A+B:", addition)

# Vector subtraction
subtraction = vector_a - vector_b
print("Vector subtraction A-B:", subtraction)

# Scalar multiplication
scalar = 2
multiplication = scalar * vector_a
print("A*B:",multiplication)

# Dot product
dot_product = np.dot(vector_a, vector_b)
print("A dot B:", dot_product)

# make an array 0-9
a = np.arange(10)
print ("array:", a)
# result: [0 1 2 3 4 5 6 7 8 9]

# create specific array
a = np.zeros(10)
b = np.ones(10)
c = np.zeros(10) + 5
print("create 0 array:", a)
print("1s array:", b)
print("0s + 5:", c)
# result:
# a = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# b = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
# c = [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

# use random numbers to populate an array
a = np.random.rand(10)
print("random number array:", a)

# index/slicing
# a[-1] retrieves the last element of the array: 9
#a[1:3] slices the array from index 1 to 2: [1, 2] exclusive slicing
# a[1:5:2] slices the array from index 1 to 4 with a step of 2: [1, 3]
a = np.arange(10)
print("array a:", a)
print("a[-1]:", a[-1])
print("a[1:3]:", a[1:3])
print("a[1:5:2]:", a[1:5:2])
# identity matrix function eye()
a = np.eye(5)
print("eye matrix:", a)
# result:
# [[1. 0. 0. 0. 0.]
# [0. 1. 0. 0. 0.]
# [0. 0. 1. 0. 0.]
# [0. 0. 0. 1. 0.]
# [0. 0. 0. 0. 1.]]

# split array
a = np.array(([1,2], [3,4], [5,6]))
print("split array:", a)
# result:
# [[1 2]
# [3 4]
# [5 6]]

# dot product
v1 = np.array([1,-2, 4])
v2 = np.array([2, 5, 2])
print("vector 1:", v1)
print("vector 2:", v2)
dot_product = np.dot(v1,v2)
print("The dot product of v1 and v2 is:", dot_product)
# Orthogonality
# Two vectors are orthogonal if they are perpendicular to each other. Their dot product will equal zero.
import numpy as np

a = [0,1,0]
b = [1,0,0]
v1 = np.array(a)
v2 = np.array(b)
# Vectors a and b have a dot product of zero
print ("vector 1:",v1, "vector 2:", v2)

print("dot product =", np.dot(a, b)) # result: 0

#Gram-Schmidt
# The Gram-Schmidt algorithm is used to obtain an orthonormal basis.

import numpy as np

def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))  # Initialize orthogonal matrix Q
    R = np.zeros((n, n))  # Initialize upper triangular matrix R

    for j in range(n):
        v = A[:, j]  # Take the j-th column vector of A

        for i in range(j):
            # Calculate the projection of v onto the i-th orthogonal vector in Q
            R[i, j] = np.dot(Q[:, i], A[:, j])

            # Subtract the projection from v to make it orthogonal to Q[:, i]
            v -= R[i, j] * Q[:, i]

        # Calculate the Euclidean norm of the orthogonalized vector v
        R[j, j] = np.linalg.norm(v)

        # Normalize the orthogonalized vector to obtain the j-th column of Q
        Q[:, j] = v / R[j, j]

    return Q, R

    #eigenvalues and eigenvectors
import numpy as np
A = [[0,-2],[-4,2]]
B = [[1],[1]]
v1 = np.array(A)
v2 = np.array(B)
print ("Vector A")
print (v1)

print ("Vector B")
print (v2)

np.dot(v1,v2)
print ("Multiplication of A and B.")
print (np.dot(v1,v2),"= -2B")

print ("AB is a multiple of vector B.")
print ("Because of this, vector B is an Eigenvector of vector A. -2 is the eigenvalue.")

Vector A: [1 2 3]
vector B: [4 5 6]
vector addition A+B: [5 7 9]
Vector subtraction A-B: [-3 -3 -3]
A*B: [2 4 6]
A dot B: 32
array: [0 1 2 3 4 5 6 7 8 9]
create 0 array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1s array: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
0s + 5: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
random number array: [0.96210459 0.61665421 0.43838399 0.63509273 0.03283221 0.81523357
 0.16618996 0.97316514 0.33921155 0.36775468]
array a: [0 1 2 3 4 5 6 7 8 9]
a[-1]: 9
a[1:3]: [1 2]
a[1:5:2]: [1 3]
eye matrix: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
split array: [[1 2]
 [3 4]
 [5 6]]
vector 1: [ 1 -2  4]
vector 2: [2 5 2]
The dot product of v1 and v2 is: 0
vector 1: [0 1 0] vector 2: [1 0 0]
dot product = 0
Vector A
[[ 0 -2]
 [-4  2]]
Vector B
[[1]
 [1]]
Multiplication of A and B.
[[-2]
 [-2]] = -2B
AB is a multiple of vector B.
Because of this, vector B is an Eigenvector of vector A. -2 is the eigenvalue.
